unified_mode     'true'
name             'rb-chrony'
maintainer       'Eneo Tecnología S.L.'
maintainer_email 'git@redborder.com'
license          'AGPL-3.0'
description      'Installs/Configures Chrony'
version          '0.0.5'
